spring:
  application:
    name: NotificationSystem
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:mem_db
    username: admin
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
management:
  tracing:
    export:
      enabled: false